# Site settings
title: AbouTeguh
description: 'AbouTeguh - belajar dan berinovasi'
url: 'http://abouteguh.com'
baseurl: '/'
port:    4000
host:    127.0.0.1
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Eko Teguh Widodo'
  email: me@abouteguh.com
  twitter_username: dekteguh
  facebook_username: dekteguh
  github_username:  dekteguh
  linkedin_username:  dekteguh

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
